name: "BigClown BCG"
version: 0.13
slug: "hardwario_bcg"
description: "Addon for BigClown USB radio dongle!"
map:
  - config:rw
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: "application"
devices: 
  - "/dev/ttyUSB0"
options:
  config_file: "/config/bcg_config.yaml"
schema:
  config_file: str

